Repository Misoto22/Paw-Forum, pull requests merged in 2024-05, with the labels that each got.

#18 requirements updated
  app/requirements.txt
Labels: bug

#22 Add login, logout, sign up function
  app/app.py
  app/model.py
Labels: enhancement

#28 run.sh updated
  run.sh
Labels: bug, enhancement

#29 Issue 14 link existing page
  .gitignore
  app/models.py
  app/routes.py
  app/templates/index.html
Labels: bug

#30 Jinja2 syntax introduced for running on flask
  README.md
  app/routes.py
  app/templates/PostCreate.html
  app/templates/Profile.html
  app/templates/SignIn.html
  app/templates/Signup.html
  app/templates/base.html
  app/templates/components/footer.html
  app/templates/components/forum_detail.html
  app/templates/components/forum_topic.html
  app/templates/components/nav-unlog.html
  app/templates/components/nav_logged_out.html
  app/templates/components/post_reply.html
  app/templates/index.html
  app/templates/login.html
  app/templates/post_create.html
  app/templates/register.html
  run.py
  run.sh
Labels: bug

#35 Page Titles defined in routes.py
  app/routes.py
  app/templates/Profile.html
  app/templates/base.html
  app/templates/index.html
  app/templates/login.html
  app/templates/register.html
  app/templates/reply.html
Labels: enhancement

#38 Issue 20 user register/login
  .gitignore
  app/__init__.py
  app/config.py
  app/models.py
  app/requirements.txt
  app/routes.py
  app/templates/base.html
  app/templates/login.html
  app/templates/register.html
  app/templates/signup.html
  app/templates/users.html
Labels: bug, enhancement

#48 basic unit test cases added
  tests/__init__.py
  tests/test_app.py
Labels: enhancement

#49 File Structure, Instruction for run and tests updated
  README.md
Labels: documentation

#50 test_app.py split into test_models and test_routes
  tests/test_models.py
  tests/test_routes.py
Labels: Testing

#52 more negative and edge cases for models.py and bug fixed accordingly
  app/models.py
  tests/test_app.py
  tests/test_models.py
Labels: bug, enhancement, Testing

#56 more negative and edge cases for routes.py and bug fixed accordingly
  app/routes.py
  app/templates/error_pages/404.html
  app/templates/error_pages/500.html
  tests/test_routes.py
Labels: bug, enhancement, Testing

#81 New task writes to Waitinglist now
  app/routes.py
Labels: enhancement

#85 like function works now
  app/routes.py
  app/templates/post_detail.html
Labels: bug, enhancement

#86 like button turns red after clicked
  app/requirements.txt
  app/templates/post_detail.html
Labels: enhancement

#108 Task function working now
  app/routes.py
  app/templates/components/post_reply.html
Labels: bug, enhancement

#121 ERD uploaded
  .readme_img/ERD.png
Labels: documentation

#122 ERD included in README
  README.md
Labels: documentation
